### ISSUE TITLE
Button to stop encode in progress

### ISSUE THREAD

**Issue by Qwertie-** [natis1/qencoder#17]
It would be useful to be able to stop an encode without having to close the program. Would make testing the speed of different settings a lot easier.

**Comment by natis1** [comment]
This seems like a reasonable idea. There's some disgustingness going on with the threading that will make doing this a bit weird on windows but I will see what I can do. Also stopping an encode mid encode does not give a representative speed amount because speed is only tracked during the second pass so it will probably be an underestimate until it has completed all the chunks.

**Comment by natis1** [comment]
Fixed in the latest commit. Will come to the release versions soonish but the next release is gonna take a ton of testing before I put it out.
