### ISSUE TITLE
qencoder hangs upon launch

### ISSUE THREAD

**Issue by sturmen** [natis1/qencoder#2]
Windows 10
Intel i9-9900K

I downloaded the Windows binary 7z file from the release tag, extracted the contents, and double-clicked qencoder.exe to run it. It simply launches a command prompt and hangs:
![image](https://user-images.githubusercontent.com/169858/81319733-11e88c80-905e-11ea-8fd4-c7ea9b3f57ff.png)

I also tried to run the python script directly using the Linux instructions, but that early-returns immediately. Is there any debugging steps I can try?

**Comment by natis1** [comment]
Hey, not saying this is 100% why, but qencoder's windows version uses pyinstaller which is notoriously slow to run. Once the prompt opens, allow the program a minute or so to start. This does not affect encoding performance since it uses an external tool for it. I would like to fix this though, but I'm not 100% sure how else to distribute python executables on windows so people without terminal experience can run them.

As for Linux, run the python program from a terminal and if it exits without opening a window report the error that you get as a new issue and I can fix it.

**Comment by natis1** [comment]
Hey. Feel free to reopen this if the pyinstaller version never starts.

**Comment by sturmen** [comment]
Just tested v1.1.1 and it no longer hangs. Thanks!
