### ISSUE TITLE
Failed To Split Video on (Windows 10)

### ISSUE THREAD

**Issue by ste2w** [natis1/qencoder#22]
[log.log](https://github.com/natis1/qencoder/files/5020316/log.log)
so I don't know this has been brought up but I just started using this program a few days ago and it worked great the first video I encoded so I went and loaded up another video and it gave me this (Ive Attached the log it gave)

**Comment by ste2w** [comment]
I also meant to say I know the video im used is not corrupt cause ive watched it from beginning to end

**Comment by natis1** [comment]
Hey, thanks for the report. Pyscenedetect on windows seems to use its own version of ffmpeg and other libraries that can really mess with things. Unfortunately because of a bug, using the first pass based splitting does not yet seem to fix this.

However the latest master does have a fix for this, so the next version I release should fix this.

**Comment by ste2w** [comment]
awesome i look forward to it i had used the exact same settings as the first video and that one worked fine i was thinkin what the hell did i do! lol but thank you for your reply! have a good day ill close this out and wait! :)

**Comment by ste2w** [comment]
also I don't know if this ok or not but I had another issue but I wasn't quite sure if I should add it as another "issue" but I was goin to try out the Vmaf but it said something about not finding a .pikl file?? where would I find that??
