### ISSUE TITLE
how to disable crf?? (Windows)

### ISSUE THREAD

**Issue by ste2w** [natis1/qencoder#23]
so I just updated to the newest version and am currently trying to figure out how to disable the crf I was hoping to try out the target vmaf but I haven't figured out how to disable the crf yet is it simple or am I missing something?? sorry for the back to back post btw im new to this type of thing lol

**Comment by natis1** [comment]
Target vmaf can only be run in q/crf mode (which are, for vp8/9 and av1, synonymous). It does not support vbr. aom and vpxenc's "vbr" modes simply find the closest q value to the bitrate that you request. This is why you may often request a bitrate of x and get something 10-20% different or more.

You can enable variable bitrate but not in combination with target vmaf because target vmaf tests the different q values directly to find the optimal one. The problem with testing bitrates instead is that two bitrates close together could have the same corrisponding q value, and this would give the binary search algorithm a hard time deciding an optimal bitrate. This definitely could be worked around but I do not have the mathematical knowledge to do so.

**Comment by natis1** [comment]
If you want to limit the bitrate of target vmaf, you are encouraged to go to the custom command line tab, and switch it to cq mode. with --end-usage=cq cq mode can have a limited bitrate set by adding the following command line options:

```
--target-bitrate=X --overshoot-pct=X
```
target bitrate is in kbps and overshoot pct is the maximum percentage over that target bitrate it will go in high complexity scenes. target vmaf is not designed for this kind of operation though.

**Comment by ste2w** [comment]
oh ok thanks i was just goin off of what the program said to do which was disable crf and boost lol but thank you for clarifying :) have a good day/night!

**Comment by natis1** [comment]
Actually, I am reopening this because I realized that my wording is ambiguous and as a note to me to change it for the next version. It says:
"Requires crf and darkboost disabled"
What I meant was: "Requires crf enabled and darkboost disabled" but I can understand how it could be read the other way

**Comment by ste2w** [comment]
oh! ok yeah I was like confused XD its all good no worries :)
