### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by correveidile** [natis1/qencoder#7]
Sorry if I am spaming with so many issues, I am not experienced in Github but I have readed that one has to open one individual issue for every bug report, commentary, etc. If you prefer all the commentaries in one unique issue, please, just tell me and I shall do it.

Well, here I wanted to suggest a few improvements for the interface:

- Use the native KDE (or whatever desktop is using each user) file picker instead of that tedios and spartan one that Qencoder uses now.

- Modify the descriptions for the encoding of audio. 96 Kbps "very high" is a joke. May be adecuate for pop music, and not the most subtle in regards to sound texture... I don't encode my CDs at 96 kbps not even for listening on my mobile nor I think that any audiophile woulds consider anything below 160 kps Opus or 192 OGG to be "high quality". Try to listen orchestal music, especially brass pasagges in high frecuencies compresed to 96 kbps in a, lets say, 5.000 € sound system in some audiophile shop, and then repeat the listening with the same track compresed to 256 kbps or FLAC. You shall notice the difference, and probably hear artifacts in the low bit rate compression. May be that for conversations in films, explosions, sound efects and background music 96 kbps is ok, but sincerely, not if you are riping an opera, a symphonic concert or simply a film wich gives importance to the soundtrack, like the ones of Paolo Sorrentino, Terence Malick, etc.

- Add an interface for the CRF mode, Handbrake (https://github.com/HandBrake/) has a nice one, may be you can do something similar? I am no expert but I have always readed that CRF mode is the recommended for the best overal quality.

I hope you think these sugestons are enough interesting.
Regads.

**Comment by natis1** [comment]
On point 1. I would like to look into it but I want to ensure compatibility with gnome systems and windows systems. If you could contribute code towards this effect I would be happy to accept it but I'm not familiar enough with it to do so.

On point 2. No. 96kbps is nearly transparent according to a test that xiph did explicitly on audiophiles. very high is very high for video encodes based on what movies usually contain in them. If you disagree with me on this topic then you have enough knowledge and experience to use the manual settings.

On point 3. -crf in ffmpeg and handbrake use cq for vpx and av1. yes these libs have a crf mode but they perform objectively worse so ffmpeg uses cq instead

**Comment by natis1** [comment]
Version 1.2 renames q to crf, a more familiar and easy to understand term as q is a vp8/9/av1 specific term while crf is a more generic term which is used by other codecs like h264. I will leave this issue open for suggestion 1 which I do not feel I am knowledgeable enough to do on my own.

**Comment by w-barath** [comment]
@natis re: audio bitrate for Opus high quality.  

96kbps is transparent for average content.  That's "good", not "high quality".  I am 51 years old and can only hear up to 13.3khz but I can still very plainly hear the difference between 96kbps and 128kbps for any recording which contains wind, water, waves, cymbals, flutes, whistles - anything that has a strong non-harmonic component.  

128kbps is what I would call "Very Good".  

What does the difference sound like - so you can listen for it yourself?  It sounds like the white noise component gets broken up into square bands with the volume levels of those bands changing at about 16hz instead of rising and falling naturally.  

It's not subtle.  The effect on a high quality recording of ocean waves makes that recording sound like someone's rolling their fingers on a digital keyboard with a sample of the waves, rather than being the real thing.

At 160kbps is where it becomes transparent to my poor, aging ears.  That's what I would call  "High Quality".  I suspect that someone with newer ears than me could still identify it at 160kbs once they became familiar with what they're listening for.

You don't need an audiophile setup to be able to hear the difference.  I'm using a [$99 Altech Lansing 251-series 5.1 speaker set from 2002](http://gamingillustrated.com/altec-lansing-251-speakers-review/) with a whopping 70dB SN ratio and 104dB SPL - this set was reviewed as "basic" back then.

I get that 160kbps is a large slice of the file these days when 720p AV1 content is only 3x that.  But consider this - when you're in the theatre you can turn your head to hear more clearly.  You expect to be able to hear clearly.  If a scene is blurry, you accept that.  So you'll also accept it for an entire production.  That's why we as a species happily watched NTSC for 80 years.  But if the audio is muddy / choppy / distorted / unbalanced, you'll be craning your head around trying to fix it.  Or taking your headphones off and checking the plug.  Shaking them out.  Trying a different headset.  Because it's distracting and annoying and gets in the way of getting into the content.  Now that audio is a bigger slice of the storage pie, maybe we as a species will find value in devoting the R&D into achieving some portion of the kind of quality:bitrate we see in video codecs, and then maybe 96kbps or lower will actually become "high quality".

**Comment by w-barath** [comment]
https://www.ietf.org/proceedings/80/slides/codec-4.pdf

... clearly shows even 128kbps Opus isn't transparent to average listeners for "Rock & Roll Music", and I'd bet you that the main complaint was that the cymbals sounded fake.
