### ISSUE TITLE
The Program close itself after scene detection

### ISSUE THREAD

**Issue by j-mas** [natis1/qencoder#8]
Since the newest build 0.5.19 the program doesn´t split the video and close itself. I get the log: 

21:38:32 Starting scene detection Threshold: 60
21:53:03 Found scenes: 226
21:53:03 Splitting video
Output file #0 does not contain any stream
21:53:04 Audio processing
Params: -c:a ac3 -b:a 256k -af aformat=channel_layouts="7.1|5.1|stereo"
[NULL @ 0000018b950eb740] Unable to find a suitable output format for 'C:\qencoder\temp_01'
C:\qencoder\temp_01: Invalid argument

Have you any idea what can I do?

**Comment by natis1** [comment]
Hi, this is a known issue on windows. If you are a windows user it's strongly recommended you use the release builds and not git builds because those are the only ones I test on all platforms. it's because I am doing something stupid in qt. I need to rewrite large segments of code to fix this. I am working on it today.

**Comment by j-mas** [comment]
Thank you for your answer! I'm a Windows 10 user. It would be nice if you fix the problem because the new build saves the custom settings! This is very usefull for me! Thank you!

**Comment by natis1** [comment]
Fixed in the latest version
